### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [jakov-kavcic/APPR-2015-16#3]
Poročila ti ne prevede, ker se v njem nanašaš na spremenljivke iz vzorca. Del, ki je ostal iz vzorca, pobriši; seveda dodaj še kak graf iz tvojih podatkov.

Opozoril bi še, da za hiperpovezave ne sme biti presledkov med `]` in `(` (v `README.md` imaš v redu). Če hočeš imeti seznam, pred njim in za njim pusti prazno vrstico.

**Comment by jakov-kavcic** [comment]
Mislim da sem uredil napake.

**Comment by jaanos** [comment]
V redu, bom dodal povezavo.

Da ti ne bo izpisovalo sporočil ob uvozu knjižnic v poročilo, premakni še ukaze `library` iz `uvoz.r` v `lib/libraries.r`.

**Comment by jakov-kavcic** [comment]
Imam še eden problem in sicer ko prevedem v pdf mi na sredini izpiše:

\##Warning: package 'ggplot2' was built under R version 3.2.3
\#### Attaching package: 'dplyr'
\#### The following objects are masked from 'package:stats':
\####     filter, lag
\#### The following objects are masked from 'package:base':
\####     intersect, setdiff, setequal, union
\###### Attaching package: 'nlme'
\#### The following object is masked from 'package:dplyr':
\####     collapse"

Kaj bi me morda lahko usmerili k problemu?

**Comment by jaanos** [comment]
Kot sem zgoraj napisal, lahko premakneš ukaze `library` iz `uvoz.r` v `lib/libraries.r` (klic te bi potem moral v poročilu odkomentirati); lahko pa pri kodnem bloku, kjer kličeš `uvoz.r`, dodaš parametra `message=FALSE` in `warning=FALSE`. `echo` lahko tudi nastaviš na `FALSE`, saj ni potrebno izpisovati tega uvoza (pa tudi drugod ni treba izpisovati ukazov).

**Comment by jakov-kavcic** [comment]
Najlepša hvala! Mi je uspelo odstraniti. Drugače pa samo opozorilo ne nakazuje na problem?
Sprašujem ker je sporočilo izginilo le ko sem dal warning=FALSE. Sem pa premaknil vse funkcije library() v ustrezno skripto.

**Comment by jaanos** [comment]
Opozorila pri uvozu knjižnic ponavadi niso problem - večinoma povedo, da je bila neka knjižnica zgrajena pod drugo različico R-ja. Opozorila med samim izvajanjem programa je treba vzeti nekoliko resneje, saj lahko opozorijo na npr. neuspele pretvorbe v števila, zaradi katerih se je morda kak podatek izgubil.

Ko boš imel zadnjo verzijo naloženo na GitHubu, mi javi, da posodobim povezavo.

**Comment by jakov-kavcic** [comment]
Upam da sem vse popravil. 
Hvala za pomoč.

**Comment by jaanos** [comment]
V redu, sem posodobil povezavo.
